version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
